# Generated by Django 4.2.1 on 2023-05-30 19:23

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to=posts.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
